version: '3'

services:
  fashion:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    volumes:
      - './:/workspace'
    # ports:
    #   - '8000:8000'
    shm_size: '32gb'
    tty: true
    stdin_open: true
    working_dir: /workspace
    # command: 'python server.py'
